# TASK 1(Data Cleaning and Preprocessing)

In [1]:
##Importing Packages
import pandas as pd

In [2]:
## Importing DataSet
SPD = pd.read_csv("2) Stock Prices Data Set.csv")
SPD

       symbol        date      open      high       low     close    volume
0         AAL  2014-01-02   25.0700   25.8200   25.0600   25.3600   8998943
1        AAPL  2014-01-02   79.3828   79.5756   78.8601   79.0185  58791957
2         AAP  2014-01-02  110.3600  111.8800  109.2900  109.7400    542711
3        ABBV  2014-01-02   52.1200   52.3300   51.5200   51.9800   4569061
4         ABC  2014-01-02   70.1100   70.2300   69.4800   69.8900   1148391
...       ...         ...       ...       ...       ...       ...       ...
497467    XYL  2017-12-29   68.5300   68.8000   67.9200   68.2000   1046677
497468    YUM  2017-12-29   82.6400   82.7100   81.5900   81.6100   1347613
497469    ZBH  2017-12-29  121.7500  121.9500  120.6200  120.6700   1023624
497470   ZION  2017-12-29   51.2800   51.5500   50.8100   50.8300   1261916
497471    ZTS  2017-12-29   72.5500   72.7600   72.0400   72.0400   1704122

[497472 rows x 7 columns]

In [3]:
## Checking for Missing Values
SPD.isnull().sum()

symbol     0
date       0
open      11
high       8
low        8
close      0
volume     0
dtype: int64

In [4]:
SPD.sort_values(by=['symbol', 'date'])

       symbol        date   open    high    low  close   volume
57          A  2014-01-02  57.10  57.100  56.15  56.21  1916160
540         A  2014-01-03  56.39  57.345  56.26  56.92  1866651
1023        A  2014-01-06  57.40  57.700  56.56  56.64  1777472
1506        A  2014-01-07  56.95  57.630  56.93  57.45  1463208
1989        A  2014-01-08  57.33  58.540  57.17  58.39  2659468
...       ...         ...    ...     ...    ...    ...      ...
495451    ZTS  2017-12-22  72.30  72.370  71.79  71.99  1345683
495956    ZTS  2017-12-26  72.40  72.550  71.90  72.34   792134
496461    ZTS  2017-12-27  72.59  72.690  72.25  72.45  1159771
496966    ZTS  2017-12-28  72.49  72.600  72.14  72.39   710499
497471    ZTS  2017-12-29  72.55  72.760  72.04  72.04  1704122

[497472 rows x 7 columns]

In [5]:
## Imputing missing values by combining forward and before data
SPD[['open', 'high', 'low']] = (
    SPD.groupby('symbol')[['open', 'high', 'low']]
    .ffill()
    .bfill()
)

In [6]:
SPD.isnull().sum()

symbol    0
date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64

In [7]:
## Checking for duplicate rows
SPD.duplicated().sum()

np.int64(0)

In [8]:
## CHECKING FOR INCONSISTENT DATA FORMATS
## Understanding Data Types
SPD.dtypes

symbol     object
date       object
open      float64
high      float64
low       float64
close     float64
volume      int64
dtype: object

In [9]:
## Standardizing the Date format
SPD.date.head()

0    2014-01-02
1    2014-01-02
2    2014-01-02
3    2014-01-02
4    2014-01-02
Name: date, dtype: object

In [10]:
SPD.date = pd.to_datetime(SPD.date, errors='coerce')
SPD.date.head()

0   2014-01-02
1   2014-01-02
2   2014-01-02
3   2014-01-02
4   2014-01-02
Name: date, dtype: datetime64[ns]

In [11]:
SPD.dtypes

symbol            object
date      datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
dtype: object